
/* Drop Tables */

DROP TABLE BOARD CASCADE CONSTRAINTS;
DROP TABLE MEMBER CASCADE CONSTRAINTS;




/* Create Tables */

CREATE TABLE BOARD
(
	NO number NOT NULL,
	TITLE nvarchar2(200) NOT NULL,
	CONTENT nvarchar2(2000) NOT NULL,
	HITCOUNT number DEFAULT 0,
	HEARTCOUNT number DEFAULT 0,
	POSTDATE date DEFAULT SYSDATE,
	USER_EMAIL nvarchar2(50) NOT NULL,
	PRIMARY KEY (NO)
);


CREATE TABLE MEMBER
(
	USER_EMAIL nvarchar2(50) NOT NULL,
	USER_PHONE nvarchar2(15) NOT NULL,
	USER_NAME nvarchar2(30) NOT NULL,
	USER_PASSWORD nvarchar2(100) NOT NULL,
	USER_GENDER nvarchar2(4) NOT NULL,
	USER_INTER nvarchar2(30) NOT NULL,
	USER_EDUCATION nvarchar2(10) NOT NULL,
	USER_SELF nvarchar2(1000) NOT NULL,
	USER_SINGINDATE date DEFAULT SYSDATE,
	PRIMARY KEY (USER_EMAIL)
);



/* Create Foreign Keys */

ALTER TABLE BOARD
	ADD FOREIGN KEY (USER_EMAIL)
	REFERENCES MEMBER (USER_EMAIL)
;



